name: ecommerce
description: "E-Commerce app"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.4 <4.0.0"

dependencies:
  dartz: ^0.10.1
  dio: ^5.6.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_screenutil: ^5.9.0
  fluttertoast: ^8.2.8
  get_it: ^7.2.0

  injectable: ^2.4.2

  lottie: ^3.1.2
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_lints: ^2.0.0
  build_runner: ^2.4.9
  injectable_generator: ^2.6.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/
